# Generated by Django 2.0.2 on 2018-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='df_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
