export const FETCH_DATASETS = 'FETCH_DATASETS';
export const NEW_DATASET = 'NEW_DATASET';
export const FETCH_MP2 = 'FETCH_MP2';
export const FETCH_MP2_SCATTER = 'FETCH_MP2_SCATTER';
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const FETCH_FMT = 'FETCH_FMT';
export const FETCH_SEQ_SETS = 'FETCH_SEQ_SETS';